### ISSUE TITLE
trained network

### ISSUE THREAD

**Issue by ThibaultGROUEIX** [chaene/hsp#2]
the parameters.lua file from the trained network suggests that it has been trained on all 13 categories. Can you confirm this please ? Great work by the way !

**Comment by chaene** [comment]
Yes this is correct it was trained on the 13 categories.

**Comment by ThibaultGROUEIX** [comment]
Thanks :)

**Comment by chaoer** [comment]
@ThibaultGROUEIX 
Hi， did you try to train this network?
